use_nerdfont = true
bitrate = 320
cover_max_scale = 2

[theme]
background = "#262626"
primary = "#bcbcbc"
secondary = "#ffff87"
title = "#ffff87"
playing = "#ff0055"
playing_selected = "#ff0055"
playing_bg = "#262626"
highlight = "white"
highlight_bg = "#444444"
error = "white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "#af87ff"
statusbar_bg = "#af87ff"
cmdline = "white"
cmdline_bg = "#262626"
search_match = "#af87ff"
